update pipelines and readmes

diff --git a/.github/workflows/lf-api-client-core.yml b/.github/workflows/lf-api-client-core.yml
--- a/.github/workflows/lf-api-client-core.yml
+++ b/.github/workflows/lf-api-client-core.yml
@@ -1,19 +1,16 @@
-name: lf-repository-api-client-js-CI
+name: lf-api-client-core-js-CI
 
 on:
   push:
-    branches:
-      - v2
+    branches: ['\d+.x']
   pull_request:
-    branches:
-      - v2
+    branches: ['\d+.x']
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
 env:
-  API_VERSION: 'v2'
-  NPM_VERSION: '1.0.2'
+  NPM_VERSION: '1.1.12'
   GITHUB_PAGES_BRANCH: 'gh-pages'
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
@@ -34,89 +31,7 @@ jobs:
       - name: Setup Node.js environment
         uses: actions/setup-node@v2.5.1
         with:
-          node-version: '20'
-
-      - name: Install pnpm
-        run: npm install pnpm -g
-
-      - name: PNPM install
-        run: pnpm install
-
-      - name: NPM run build
-        run: npm run build
-
-      - name: Echo NPM package version
-        run: echo ${{ env.NPM_VERSION }}
-
-      - name: Upload a build artifact
-        uses: actions/upload-artifact@v2.3.1
-        with:
-          name: npm-publish-artifact
-          # A file, directory or wildcard pattern that describes what to upload
-          path: |
-            ./dist
-            ./package.json
-            ./README.md
-            ./LICENSE
-
-  test:
-    runs-on: ubuntu-latest
-    needs: [build]
-    steps:
-      - uses: actions/checkout@v2
-
-      - name: Setup Node.js environment
-        uses: actions/setup-node@v2.5.1
-        with:
-          node-version: '20'
-
-      - name: Install pnpm
-        run: npm install pnpm -g
-
-      - name: PNPM install
-        run: pnpm install
-
-      - name: NPM test on cloud (node environment)
-        id: test-cloud-node
-        env:
-          ACCESS_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY }}
-          SERVICE_PRINCIPAL_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
-          REPOSITORY_ID: ${{ secrets.DEV_CA_PUBLIC_USE_REPOSITORY_ID_1 }}
-          AUTHORIZATION_TYPE: ${{ secrets.AUTHORIZATION_TYPE }}
-          TEST_HEADER: ${{ secrets.TEST_HEADER }}
-        run: pnpm --filter @laserfiche/lf-repository-api-client-v2 run test:node
-
-      - name: NPM test on cloud (browser environment)
-        id: test-cloud-browser
-        env:
-          ACCESS_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY }}
-          SERVICE_PRINCIPAL_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
-          REPOSITORY_ID: ${{ secrets.DEV_CA_PUBLIC_USE_REPOSITORY_ID_3 }}
-          AUTHORIZATION_TYPE: ${{ secrets.AUTHORIZATION_TYPE }}
-          TEST_HEADER: ${{ secrets.TEST_HEADER }}
-        run: pnpm --filter @laserfiche/lf-repository-api-client-v2 run test:browser
-
-      - name: Test report
-        uses: dorny/test-reporter@v1
-        if: success() || failure() # run this step even if previous step failed
-        with:
-          name: Jest Test Results
-          path: ./*.xml
-          reporter: jest-junit
-          only-summary: 'false'
-          list-tests: 'failed'
-          fail-on-error: 'false'
-
-  build-documentation:
-    runs-on: ubuntu-latest
-    needs: [build, test]
-    steps:
-      - uses: actions/checkout@v2
-
-      - name: Setup Node.js environment
-        uses: actions/setup-node@v2.5.1
-        with:
-          node-version: '20'
+          node-version: "20"
 
       - name: Install pnpm
         run: npm install pnpm -g
@@ -125,163 +40,239 @@ jobs:
         run: pnpm install
 
       - name: PNPM run build
-        run: pnpm run build --filter @laserfiche/lf-repository-api-client-v2
+        run: pnpm run build --filter @laserfiche/lf-api-client-core
+
+      - name: Echo NPM package version
+        run: echo ${{ env.NPM_VERSION }}
+
+      - name: Upload a Build Artifact
+        uses: actions/upload-artifact@v2.3.1
+        with:
+          name: npm-publish-artifact
+          # A file, directory or wildcard pattern that describes what to upload
+          path: |
+            ./packages/lf-api-client-core/dist
+            ./packages/lf-api-client-core/package.json
+            ./packages/lf-api-client-core/README.md
+            ./LICENSE
+
+
+  test:
+    runs-on: ubuntu-latest
+    needs: [ build ]
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Echo build number
+        run: echo ${{github.run_id}}
+
+      - name: Setup Node.js environment
+        uses: actions/setup-node@v2.5.1
+        with:
+          node-version: "20"
+
+      - name: Install pnpm
+        run: npm install pnpm -g
+
+      - name: PNPM install
+        run: pnpm install
+
+      - name: Npm test on cloud
+        id: test-cloud
+        env:
+          ACCESS_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY }}
+          ACCESS_KEY_JSON: ${{ secrets.ACCESS_KEY_JSON }}
+          SERVICE_PRINCIPAL_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
+        run: pnpm --filter @laserfiche/lf-api-client-core run test:Cloud
+
+      - name: Npm test on self-hosted
+        if: always() && (steps.test-cloud.outcome == 'success' || steps.test-cloud.outcome == 'failure')
+        env:
+          REPOSITORY_ID: ${{ secrets.APISERVER_REPOSITORY_ID }}
+          APISERVER_USERNAME:  ${{ secrets.APISERVER_USERNAME }}
+          APISERVER_PASSWORD:  ${{ secrets.APISERVER_PASSWORD }}
+          APISERVER_REPOSITORY_API_BASE_URL:  ${{ secrets.APISERVER_REPOSITORY_API_BASE_URL }}
+          ACCESS_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY }}
+          ACCESS_KEY_JSON: ${{ secrets.ACCESS_KEY_JSON }}
+          SERVICE_PRINCIPAL_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
+        run: pnpm --filter @laserfiche/lf-api-client-core run test:SelfHosted
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: Jest Test Results
+          path: ./*.xml
+          reporter: jest-junit
+          only-summary: "false"
+          list-tests: "failed"
+          fail-on-error: "false"
+
+
+  build-documentation:
+    runs-on: ubuntu-latest
+    needs: [ build, test ]
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Setup Node.js environment
+        uses: actions/setup-node@v2.5.1
+        with:
+          node-version: "20"
+
+      - name: Install pnpm
+        run: npm install pnpm -g
+
+      - name: PNPM install
+        run: pnpm install
 
       - name: Install typedoc
         run: pnpm install typedoc
 
       - name: Create temporary directory
-        run: mkdir -p ./docs_temp
+        run: mkdir -p ./docs_temp/${{ github.ref_name }}
 
       - name: Generate typedoc docs
-        run: npx typedoc ./packages/lf-repository-api-client-js/index.ts --out ./docs_temp --excludePrivate --includeVersion
+        run: npx typedoc ./packages/lf-api-client-core-js/index.ts --out ./docs_temp/${{ github.ref_name }} --excludePrivate --includeVersion
 
-      - name: Upload a build artifact
+      - name: Upload a Build Artifact
         uses: actions/upload-artifact@v2.3.1
         with:
           name: documentation-artifact
           # A file, directory or wildcard pattern that describes what to upload
-          path: ${{ github.workspace }}/docs_temp
+          path: ${{ github.workspace }}/docs_temp/${{ github.ref_name }}
 
-      - name: Delete temporary directory
+      - name: delete temporary directory
         run: rm -r ./docs_temp
 
   publish-preview-package:
     runs-on: ubuntu-latest
     environment: preview
     if: ${{ github.run_attempt != 1 }}
-    needs: [build, test, build-documentation] # wait for build to finish
+    needs: [ build, test, build-documentation ] # wait for build to finish
     steps:
       - uses: actions/checkout@v2
         with:
           ref: ${{ github.sha }}
 
-      - name: Download a build artifact
-        uses: actions/download-artifact@v2.1.0
+      - name: Download a Build Artifact
+        uses: actions/download-artifact@v3.0.0
         with:
           name: npm-publish-artifact
 
       - name: Setup Node.js environment
         uses: actions/setup-node@v2.5.1
         with:
-          node-version: '20'
+          node-version: "20"
 
       - name: Install pnpm
         run: npm install pnpm -g
 
-      - name: Set NpmPackageVersion as preview version from downloaded artifact
+      - name: PNPM install
+        run: pnpm install
+
+      - name: set NpmPackageVersion as preview version from downloaded artifact
         run: echo "NpmPackageVersion=${{ env.NPM_VERSION }}--preview-${{ github.run_id }}" >> $GITHUB_ENV
 
-      - name: PNPM version
+      - name: pnpm version
         run: pnpm version ${{ env.NpmPackageVersion }} --no-git-tag-version
-        env:
-          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
-          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
-          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
-          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}
 
-      - name: PNPM publish
+      - name: pnpm publish
         run: pnpm publish  --access public  --tag next
         env:
-          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
-          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
-          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
-          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}
+          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 
       - name: Tag commit
         uses: rickstaa/action-create-tag@v1
         with:
-          tag: ${{ env.API_VERSION }}-${{ env.NpmPackageVersion }}
+          tag: ${{ env.NpmPackageVersion }}
           commit_sha: ${{ github.sha }}
           message: Workflow run ${{github.server_url}}/${{github.repository}}/actions/runs/${{ github.run_id}}
+
 
   publish-production-package:
     runs-on: ubuntu-latest
     environment: production
     if: ${{ github.run_attempt != 1 }}
-    needs: [build, test, build-documentation]
+    needs: [ build, test, build-documentation ]
     steps:
       - uses: actions/checkout@v2
         with:
           ref: ${{ github.sha }}
 
-      - name: Download a build artifact
-        uses: actions/download-artifact@v2.1.0
+      - name: Download a Build Artifact
+        uses: actions/download-artifact@v3.0.0
         with:
           name: npm-publish-artifact
 
       - name: Setup Node.js environment
         uses: actions/setup-node@v2.5.1
         with:
-          node-version: '20'
-          
+          node-version: "20"
+
       - name: Install pnpm
         run: npm install pnpm -g
 
-      - name: PNPM version
+      - name: pnpm version
         run: pnpm version ${{ env.NPM_VERSION }} --no-git-tag-version --allow-same-version
-        env:
-          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
-          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
-          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
-          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}
 
-      - name: PNPM publish
+      - name: pnpm publish
         run: pnpm publish  --access public  --tag latest
         env:
-          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
-          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
-          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
-          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}
+          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 
       - name: Tag commit
         uses: rickstaa/action-create-tag@v1
         with:
-          tag: ${{ env.API_VERSION }}-${{ env.NPM_VERSION }}
+          tag: ${{ env.NPM_VERSION }}
           commit_sha: ${{ github.sha }}
           message: Workflow run ${{github.server_url}}/${{github.repository}}/actions/runs/${{ github.run_id}}
 
-  # NEED TO FIGURE OUT DOCUMENTATION
+  # NEED TO FIX DOCUMENTATION
   # publish-documentation:
   #   runs-on: ubuntu-latest
   #   timeout-minutes: 10
   #   environment: github-pages
-  #   needs: [publish-production-package]
+  #   needs: [ publish-production-package ]
   #   steps:
   #     - name: Set DOCUMENTATION_VERSION environment variable
   #       run: |
-  #         npm_version=${{ env.NPM_VERSION }}
-  #         major_version=${npm_version%%.*}
-  #         documentation_version=$major_version.x
-  #         echo $documentation_version
-  #         echo DOCUMENTATION_VERSION=$documentation_version >> $GITHUB_ENV
+  #         if [[ '${{ github.event_name }}' == 'pull_request' ]]; then
+  #           echo 'DOCUMENTATION_VERSION=${{ github.base_ref }}' >> $GITHUB_ENV
+  #         elif [[ '${{ github.ref_protected }}' == 'true' && '${{ github.ref_type }}' == 'branch' ]]; then
+  #           echo 'DOCUMENTATION_VERSION=${{ github.ref_name }}' >> $GITHUB_ENV
+  #         else
+  #           echo '::error::Unable to publish documentation for the current branch.'
+  #           exit 1
+  #         fi
 
   #     - name: Print DOCUMENTATION_VERSION environment variable
   #       run: |
-  #         echo 'Publishing documentation to ${{ env.GITHUB_PAGES_BRANCH }} for ${{ env.API_VERSION }} ${{ env.DOCUMENTATION_VERSION }}.'
+  #         echo 'Publishing documentation to ${{ env.GITHUB_PAGES_BRANCH }} for ${{ env.DOCUMENTATION_VERSION }}.'
 
   #     - uses: actions/checkout@v3
   #       with:
   #         ref: ${{ env.GITHUB_PAGES_BRANCH }}
 
   #     - name: Delete documentation directory
-  #       run: rm -f -r ./docs/${{ env.API_VERSION }}/${{ env.DOCUMENTATION_VERSION }}
+  #       run: rm -f -r ./docs/${{ env.DOCUMENTATION_VERSION }}
 
   #     - name: Create documentation directory
-  #       run: mkdir -p ./docs/${{ env.API_VERSION }}/${{ env.DOCUMENTATION_VERSION }}
+  #       run: mkdir -p ./docs/${{ env.DOCUMENTATION_VERSION }}
 
   #     - name: Download documentation build artifact
   #       uses: actions/download-artifact@v3.0.0
   #       with:
   #         name: documentation-artifact
-  #         path: ./docs/${{ env.API_VERSION }}/${{ env.DOCUMENTATION_VERSION }}
+  #         path: ./docs/${{ env.DOCUMENTATION_VERSION }}
 
-  #     - name: Create a pull request
+  #     - name: Create Pull Request
   #       uses: peter-evans/create-pull-request@v4.2.3
   #       with:
-  #         branch: ${{ env.GITHUB_PAGES_BRANCH }}-${{ env.API_VERSION }}-${{ env.DOCUMENTATION_VERSION }}-patch
+  #         branch: ${{ env.GITHUB_PAGES_BRANCH }}-${{ env.DOCUMENTATION_VERSION }}-patch
   #         delete-branch: true
-  #         title: 'Automated documentation update for ${{ env.API_VERSION }} ${{ env.DOCUMENTATION_VERSION }} by action ${{ github.run_id }}'
-  #         commit-message: 'Automated documentation update for ${{ env.API_VERSION }} ${{ env.DOCUMENTATION_VERSION }} by action ${{ github.run_id }}'
-  #         body: 'Automated documentation update for ${{ env.API_VERSION }} ${{ env.DOCUMENTATION_VERSION }} by action ${{ github.run_id }}'
+  #         title: "Automated documentation update for ${{ env.DOCUMENTATION_VERSION }} by action ${{ github.run_id }}"
+  #         commit-message: "Automated documentation update for ${{ env.DOCUMENTATION_VERSION }} by action ${{ github.run_id }}"
+  #         body: "Automated documentation update for ${{ env.DOCUMENTATION_VERSION }} by action ${{ github.run_id }}"
   #         assignees: ${{ github.actor }}
+
