add repository-api-client-v1

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,8 +13,9 @@ on:
   workflow_dispatch:
 
 env:
-  NPM_VERSION: '1.1.12'
-  GITHUB_PAGES_BRANCH: 'gh-pages'
+  NPM_API_CLIENT_V1_VERSION: '1.1.4'
+  NPM_API_CLIENT_V2_VERSION: '1.0.2'
+  NPM_CLIENT_CORE_VERSION: '1.1.12'
 
 jobs:
   build_libraries:
@@ -43,9 +44,7 @@ jobs:
 
       - name: PNPM run build
         run: pnpm run build
-
-      - name: Echo NPM package version
-        run: echo ${{ env.NPM_VERSION }}
+=
 
       - name: Copy license
         run: cp ./LICENSE ./packages/lf-api-client-core-js/LICENSE
@@ -60,6 +59,20 @@ jobs:
             ./packages/lf-api-client-core-js/package.json
             ./packages/lf-api-client-core-js/README.md
             ./packages/lf-api-client-core-js/LICENSE
+
+      - name: Copy license
+        run: cp ./LICENSE ./packages/lf-repository-api-client-v1/LICENSE
+
+      - name: Upload a build artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: npm-api-client-v1-publish-artifact
+          # A file, directory or wildcard pattern that describes what to upload
+          path: |
+            ./packages/lf-repository-api-client-v1/dist
+            ./packages/lf-repository-api-client-v1/package.json
+            ./packages/lf-repository-api-client-v1/README.md
+            ./packages/lf-repository-api-client-v1/LICENSE
 
       - name: Copy license
         run: cp ./LICENSE ./packages/lf-repository-api-client-v2/LICENSE
@@ -123,6 +136,29 @@ jobs:
           list-tests: "failed"
           fail-on-error: "false"
 
+      - name: NPM @laserfiche/lf-repository-api-client run all tests
+        env:
+          ACCESS_KEY: ${{ secrets.DEV_US_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY }}
+          SERVICE_PRINCIPAL_KEY: ${{ secrets.DEV_US_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
+          REPOSITORY_ID:  ${{ secrets.APISERVER_REPOSITORY_ID }}
+          APISERVER_USERNAME: ${{ secrets.APISERVER_USERNAME }}
+          APISERVER_PASSWORD: ${{ secrets.APISERVER_PASSWORD }}
+          APISERVER_REPOSITORY_API_BASE_URL: ${{ secrets.APISERVER_REPOSITORY_API_BASE_URL }}
+          AUTHORIZATION_TYPE: ${{ secrets.APISERVER_AUTHORIZATION_TYPE }}
+          TEST_HEADER: ${{ secrets.TEST_HEADER }}
+        run: npm --filter @laserfiche/lf-repository-api-client run test:all
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: Api Client v1 Jest Test Results
+          path: ./packages/lf-repository-api-client-v1/*.xml
+          reporter: jest-junit
+          only-summary: "false"
+          list-tests: "failed"
+          fail-on-error: "false"
+
 # TODO remove unnecessary secrets
       - name: NPM test lf-repository-api-client-v2 on cloud (node environment)
         id: test-cloud-node
@@ -148,7 +184,7 @@ jobs:
         uses: dorny/test-reporter@v1
         if: success() || failure() # run this step even if previous step failed
         with:
-          name: Api Client Jest Test Results
+          name: Api Client v2 Jest Test Results
           path: ./packages/lf-repository-api-client-v2/*.xml
           reporter: jest-junit
           only-summary: 'false'
@@ -202,7 +238,7 @@ jobs:
         run: npm install pnpm -g
 
       - name: set NpmPackageVersion as preview version from downloaded artifact
-        run: echo "NpmPackageVersion=${{ env.NPM_VERSION }}--preview-${{ github.run_id }}" >> $GITHUB_ENV
+        run: echo "NpmPackageVersion=${{ env.NPM_CLIENT_CORE_VERSION }}--preview-${{ github.run_id }}" >> $GITHUB_ENV
 
       - name: pnpm version
         run: pnpm version ${{ env.NpmPackageVersion }} --no-git-tag-version
@@ -245,7 +281,7 @@ jobs:
         run: npm install pnpm -g
 
       - name: pnpm version
-        run: pnpm version ${{ env.NPM_VERSION }} --no-git-tag-version --allow-same-version
+        run: pnpm version ${{ env.NPM_CLIENT_CORE_VERSION }} --no-git-tag-version --allow-same-version
 
       - name: Set publishing config
         run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
@@ -260,7 +296,90 @@ jobs:
       - name: Tag commit
         uses: rickstaa/action-create-tag@v1
         with:
-          tag: lf-api-client-core-${{ env.NPM_VERSION }}
+          tag: lf-api-client-core-${{ env.NPM_CLIENT_CORE_VERSION }}
+          commit_sha: ${{ github.sha }}
+          message: Workflow run ${{github.server_url}}/${{github.repository}}/actions/runs/${{ github.run_id}}
+
+
+  publish-api-client-v1-preview-package:
+    runs-on: ubuntu-latest
+    environment: preview
+    if: ${{ github.run_attempt != 1 }}
+    needs: [ build_libraries, test_libraries, build_documentation ]
+    steps:
+      - name: Download a Build Artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: npm-api-client-v1-publish-artifact
+
+      - name: Setup Node.js environment
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20"
+
+      - name: Install pnpm
+        run: npm install pnpm -g
+
+      - name: set NpmPackageVersion as preview version from downloaded artifact
+        run: echo "NpmPackageVersion=${{ env.NPM_API_CLIENT_V1_VERSION }}--preview-${{ github.run_id }}" >> $GITHUB_ENV
+
+      - name: pnpm version
+        run: pnpm version ${{ env.NpmPackageVersion }} --no-git-tag-version
+
+      - name: Set publishing config
+        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
+        env:
+          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
+
+      - name: pnpm publish
+        run: pnpm publish --filter @laserfiche/lf-repository-api-client --access public  --tag next --no-git-checks
+
+      - uses: actions/checkout@v4
+
+      - name: Tag commit
+        uses: rickstaa/action-create-tag@v1
+        with:
+          tag: lf-repository-api-client-v1-${{ env.NpmPackageVersion }}
+          commit_sha: ${{ github.sha }}
+          message: Workflow run ${{github.server_url}}/${{github.repository}}/actions/runs/${{ github.run_id}}
+
+
+  publish-api-client-v1-production-package:
+    runs-on: ubuntu-latest
+    environment: production
+    if: ${{ github.run_attempt != 1 }}
+    needs: [ build_libraries, test_libraries, build_documentation ]
+    steps:
+      - name: Download a Build Artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: npm-api-client-v1-publish-artifact
+
+      - name: Setup Node.js environment
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20"
+
+      - name: Install pnpm
+        run: npm install pnpm -g
+
+      - name: pnpm version
+        run: pnpm version ${{ env.NPM_API_CLIENT_V1_VERSION }} --no-git-tag-version --allow-same-version
+
+      - name: Set publishing config
+        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
+        env:
+          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
+
+      - name: pnpm publish
+        run: pnpm publish --filter @laserfiche/lf-repository-api-client --access public  --tag next --no-git-checks
+
+      - uses: actions/checkout@v4
+
+      - name: Tag commit
+        uses: rickstaa/action-create-tag@v1
+        with:
+          tag: lf-repository-api-client-v1-${{ env.NPM_API_CLIENT_V1_VERSION }}
           commit_sha: ${{ github.sha }}
           message: Workflow run ${{github.server_url}}/${{github.repository}}/actions/runs/${{ github.run_id}}
 
@@ -291,7 +410,7 @@ jobs:
         run: pnpm install
 
       - name: Set NpmPackageVersion as preview version from downloaded artifact
-        run: echo "NpmPackageVersion=${{ env.NPM_VERSION }}--preview-${{ github.run_id }}" >> $GITHUB_ENV
+        run: echo "NpmPackageVersion=${{ env.NPM_API_CLIENT_V2_VERSION }}--preview-${{ github.run_id }}" >> $GITHUB_ENV
 
       - name: PNPM version
         working-directory: ./packages/lf-repository-api-client-v2
@@ -341,7 +460,7 @@ jobs:
           NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
 
       - name: PNPM version
-        run: pnpm version ${{ env.NPM_VERSION }} --no-git-tag-version --allow-same-version
+        run: pnpm version ${{ env.NPM_API_CLIENT_V2_VERSION }} --no-git-tag-version --allow-same-version
 
       - name: PNPM publish
         working-directory: ./packages/lf-repository-api-client-v2
@@ -352,7 +471,7 @@ jobs:
       - name: Tag commit
         uses: rickstaa/action-create-tag@v1
         with:
-          tag: lf-repository-api-client-v2-${{ env.NPM_VERSION }}
+          tag: lf-repository-api-client-v2-${{ env.NPM_API_CLIENT_V2_VERSION }}
           commit_sha: ${{ github.sha }}
           message: Workflow run ${{github.server_url}}/${{github.repository}}/actions/runs/${{ github.run_id}}
 
