test yaml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -152,46 +152,55 @@ jobs:
           SERVICE_PRINCIPAL_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
         run: pnpm --filter @laserfiche/lf-api-client-core run test:Cloud
 
-      - name: pnpm test lf-api-client-core on self-hosted
-        if: always() && (steps.test-cloud.outcome == 'success' || steps.test-cloud.outcome == 'failure')
-        env:
-          REPOSITORY_ID: ${{ secrets.APISERVER_REPOSITORY_ID }}
-          APISERVER_USERNAME: ${{ secrets.APISERVER_USERNAME }}
-          APISERVER_PASSWORD: ${{ secrets.APISERVER_PASSWORD }}
-          APISERVER_REPOSITORY_API_BASE_URL: ${{ secrets.APISERVER_REPOSITORY_API_BASE_URL }}
-        run: pnpm --filter @laserfiche/lf-api-client-core run test:SelfHosted
+      # - name: pnpm test lf-api-client-core on self-hosted
+      #   if: always() && (steps.test-cloud.outcome == 'success' || steps.test-cloud.outcome == 'failure')
+      #   env:
+      #     REPOSITORY_ID: ${{ secrets.APISERVER_REPOSITORY_ID }}
+      #     APISERVER_USERNAME: ${{ secrets.APISERVER_USERNAME }}
+      #     APISERVER_PASSWORD: ${{ secrets.APISERVER_PASSWORD }}
+      #     APISERVER_REPOSITORY_API_BASE_URL: ${{ secrets.APISERVER_REPOSITORY_API_BASE_URL }}
+      #   run: pnpm --filter @laserfiche/lf-api-client-core run test:SelfHosted
 
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure() # run this step even if previous step failed
-        with:
-          name: Client Core Jest Test Results
-          path: ./packages/lf-api-client-core-js/*.xml
-          reporter: jest-junit
-          only-summary: 'false'
-          list-tests: 'failed'
-          fail-on-error: 'false'
+      # - name: Test Report lf-api-client-core
+      #   uses: dorny/test-reporter@v1
+      #   if: success() || failure() # run this step even if previous step failed
+      #   with:
+      #     name: Client Core Jest Test Results
+      #     path: ./packages/lf-api-client-core-js/*.xml
+      #     reporter: jest-junit
+      #     only-summary: 'false'
+      #     list-tests: 'failed'
+      #     fail-on-error: 'false'
 
-      - name: pnpm test @laserfiche/lf-repository-api-client run all cloud tests
+      - name: pnpm test @laserfiche/lf-repository-api-client run all cloud node tests
         env:
           ACCESS_KEY: ${{ secrets.DEV_US_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY }}
           SERVICE_PRINCIPAL_KEY: ${{ secrets.DEV_US_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
           REPOSITORY_ID_CLOUD: ${{ secrets.DEV_US_PUBLIC_USE_REPOSITORY_ID_1 }}
           AUTHORIZATION_TYPE: ${{ secrets.AUTHORIZATION_TYPE }}
           TEST_HEADER: ${{ secrets.TEST_HEADER }}
-        run: pnpm --filter @laserfiche/lf-repository-api-client run test:all
+        run: pnpm --filter @laserfiche/lf-repository-api-client run test:node
 
-      - name: pnpm test @laserfiche/lf-repository-api-client run all self-hosted tests
+      - name: pnpm test @laserfiche/lf-repository-api-client run all cloud browser tests
         env:
           ACCESS_KEY: ${{ secrets.DEV_US_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY }}
           SERVICE_PRINCIPAL_KEY: ${{ secrets.DEV_US_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
-          REPOSITORY_ID: ${{ secrets.APISERVER_REPOSITORY_ID }}
-          APISERVER_USERNAME: ${{ secrets.APISERVER_USERNAME }}
-          APISERVER_PASSWORD: ${{ secrets.APISERVER_PASSWORD }}
-          APISERVER_REPOSITORY_API_BASE_URL: ${{ secrets.APISERVER_REPOSITORY_API_BASE_URL }}
-          AUTHORIZATION_TYPE: ${{ secrets.APISERVER_AUTHORIZATION_TYPE }}
+          REPOSITORY_ID_CLOUD: ${{ secrets.DEV_US_PUBLIC_USE_REPOSITORY_ID_1 }}
+          AUTHORIZATION_TYPE: ${{ secrets.AUTHORIZATION_TYPE }}
           TEST_HEADER: ${{ secrets.TEST_HEADER }}
-        run: pnpm --filter @laserfiche/lf-repository-api-client run test:all
+        run: pnpm --filter @laserfiche/lf-repository-api-client run test:browser
+        
+      # - name: pnpm test @laserfiche/lf-repository-api-client run all self-hosted tests
+      #   env:
+      #     ACCESS_KEY: ${{ secrets.DEV_US_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY }}
+      #     SERVICE_PRINCIPAL_KEY: ${{ secrets.DEV_US_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
+      #     REPOSITORY_ID: ${{ secrets.APISERVER_REPOSITORY_ID }}
+      #     APISERVER_USERNAME: ${{ secrets.APISERVER_USERNAME }}
+      #     APISERVER_PASSWORD: ${{ secrets.APISERVER_PASSWORD }}
+      #     APISERVER_REPOSITORY_API_BASE_URL: ${{ secrets.APISERVER_REPOSITORY_API_BASE_URL }}
+      #     AUTHORIZATION_TYPE: ${{ secrets.APISERVER_AUTHORIZATION_TYPE }}
+      #     TEST_HEADER: ${{ secrets.TEST_HEADER }}
+      #   run: pnpm --filter @laserfiche/lf-repository-api-client run test:all
 
       - name: Test Report
         uses: dorny/test-reporter@v1
