Cleaned Dependencies, Ts config for lint and jest

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,7 +38,7 @@ jobs:
       - name: Setup Node.js environment
         uses: actions/setup-node@v4
         with:
-          node-version: '20'
+          node-version: '24'
 
       - name: Install pnpm
         run: npm install pnpm@latest-9 -g
@@ -120,7 +120,7 @@ jobs:
       - name: Setup Node.js environment
         uses: actions/setup-node@v4
         with:
-          node-version: '20'
+          node-version: '24'
 
       - name: Install pnpm
         run: npm install pnpm@latest-9 -g
@@ -135,7 +135,7 @@ jobs:
         run: pnpm --filter @laserfiche/lf-js-utils run test:ci
 
       - name: Test Report
-        uses: dorny/test-reporter@v1
+        uses: dorny/test-reporter@v2
         if: success() || failure() # run this step even if previous step failed
         with:
           name: JS Utils Jest Test Results
@@ -152,25 +152,25 @@ jobs:
           SERVICE_PRINCIPAL_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
         run: pnpm --filter @laserfiche/lf-api-client-core run test:Cloud
 
-      # - name: pnpm test lf-api-client-core on self-hosted
-      #   if: always() && (steps.test-cloud.outcome == 'success' || steps.test-cloud.outcome == 'failure')
-      #   env:
-      #     REPOSITORY_ID: ${{ secrets.APISERVER_REPOSITORY_ID }}
-      #     APISERVER_USERNAME: ${{ secrets.APISERVER_USERNAME }}
-      #     APISERVER_PASSWORD: ${{ secrets.APISERVER_PASSWORD }}
-      #     APISERVER_REPOSITORY_API_BASE_URL: ${{ secrets.APISERVER_REPOSITORY_API_BASE_URL }}
-      #   run: pnpm --filter @laserfiche/lf-api-client-core run test:SelfHosted
+      - name: pnpm test lf-api-client-core on self-hosted
+        if: always() && (steps.test-cloud.outcome == 'success' || steps.test-cloud.outcome == 'failure')
+        env:
+          REPOSITORY_ID: ${{ secrets.APISERVER_REPOSITORY_ID }}
+          APISERVER_USERNAME: ${{ secrets.APISERVER_USERNAME }}
+          APISERVER_PASSWORD: ${{ secrets.APISERVER_PASSWORD }}
+          APISERVER_REPOSITORY_API_BASE_URL: ${{ secrets.APISERVER_REPOSITORY_API_BASE_URL }}
+        run: pnpm --filter @laserfiche/lf-api-client-core run test:SelfHosted
 
-      # - name: Test Report lf-api-client-core
-      #   uses: dorny/test-reporter@v1
-      #   if: success() || failure() # run this step even if previous step failed
-      #   with:
-      #     name: Client Core Jest Test Results
-      #     path: ./packages/lf-api-client-core-js/*.xml
-      #     reporter: jest-junit
-      #     only-summary: 'false'
-      #     list-tests: 'failed'
-      #     fail-on-error: 'false'
+      - name: Test Report lf-api-client-core
+        uses: dorny/test-reporter@v2
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: Client Core Jest Test Results
+          path: ./packages/lf-api-client-core-js/junit-*.xml
+          reporter: jest-junit
+          only-summary: 'false'
+          list-tests: 'failed'
+          fail-on-error: 'false'
 
       - name: pnpm test @laserfiche/lf-repository-api-client run all cloud node tests
         env:
@@ -203,7 +203,7 @@ jobs:
       #   run: pnpm --filter @laserfiche/lf-repository-api-client run test:all
 
       - name: Test Report
-        uses: dorny/test-reporter@v1
+        uses: dorny/test-reporter@v2
         if: success() || failure() # run this step even if previous step failed
         with:
           name: Api Client v1 Jest Test Results
@@ -234,7 +234,7 @@ jobs:
         run: pnpm --filter @laserfiche/lf-repository-api-client-v2 run test:browser
 
       - name: Test report
-        uses: dorny/test-reporter@v1
+        uses: dorny/test-reporter@v2
         if: success() || failure() # run this step even if previous step failed
         with:
           name: Api Client v2 Jest Test Results
@@ -248,7 +248,7 @@ jobs:
         run: pnpm --filter @laserfiche/lf-api-js run test
 
       - name: Test Report
-        uses: dorny/test-reporter@v1
+        uses: dorny/test-reporter@v2
         if: success() || failure() # run this step even if previous step failed
         with:
           name: Api JS Jest Test Results
@@ -267,7 +267,7 @@ jobs:
       - name: Setup Node.js environment
         uses: actions/setup-node@v4
         with:
-          node-version: '20'
+          node-version: '24'
 
       - name: Install pnpm
         run: npm install pnpm@latest-9 -g
@@ -352,10 +352,10 @@ jobs:
           name: pnpm-api-js-types-publish-artifact
           path: ./packages/lf-api-js/types-npm-publish
 
-      - name: Setup Node.js v20 environment
+      - name: Setup Node.js v24 environment
         uses: actions/setup-node@v4
         with:
-          node-version: '20'
+          node-version: '24'
 
       - name: Update npm
         run: npm install -g npm@latest
@@ -474,10 +474,10 @@ jobs:
           name: pnpm-api-js-types-publish-artifact
           path: ./packages/lf-api-js/types-npm-publish
 
-      - name: Setup Node.js v20 environment
+      - name: Setup Node.js v24 environment
         uses: actions/setup-node@v4
         with:
-          node-version: '20'
+          node-version: '24'
 
       - name: Update npm
         run: npm install -g npm@latest
